### ISSUE TITLE
The Amp way to add images to a Post

### ISSUE THREAD

**Issue by andreabisello** [huyb1991/hugo-lamp#17]
Hi,
what is the correct/amp way to add images to a post?
i see that

`cover: "/img/cover.jpg"
`
will only used to set a post thumbnail, but cover is not used inside the article.

let's suppose i want to add some images, any suggestion to add in the right way?

thanks.

**Comment by huyb1991** [comment]
Hi there,
The `cover: "/img/cover.jpg"` is an image in the theme, please take a look on this issue (resolved) [How to… insert image in my post?](https://discourse.gohugo.io/t/solved-how-to-insert-image-in-my-post/1473). Follow this solution, you should add images in `theme`.

For me, this is not good way, because if we want to change the theme, we have to copy all images to new theme. I choose another way is upload images some where I can control and get the image url, then insert it to article.

The way to add image to article is via [amp-img shortcodes](https://github.com/huyb1991/hugo-lamp/blob/master/layouts/shortcodes/amp-img.html)
```
{{< amp-img width="width-value" height="height-value" layout="responsive" src="image-url" alt="image alt">}}
```
Replace value for `width-value`, `height-value` and `image-url` by your image, the `layout="responsive"` will display image full 100% width on mobile, take a look on [AMP Layout & media queries](https://www.ampproject.org/docs/design/responsive/control_layout).

Hope this help!
